version: '3.9'
services:
  db:
      container_name: ${PROJECT_NAME}_db
      platform: linux/x86_64
      image: library/${DB_TYPE}:${DB_VERSION}
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      ports:
        - ${DB_LOCAL_PORT}:3306
      volumes:
        - ./services/db/my.cnf:/etc/mysql/my.cnf
        - ./services/db/${DB_TYPE}/dump:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
        - ./data:/docker-entrypoint-initdb.d
      networks:
        - main_network
  phpcnt:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./services/php${PHP_VERSION}
    container_name: ${PROJECT_NAME}_php_${PHP_VERSION}
    image: ${PROJECT_NAME}_php_${PHP_VERSION}
    restart: unless-stopped
    volumes:
      - ./www/:/var/www/html/
      - ./services/php${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - ./logs/xdebug/:/var/log/xdebug/
    depends_on:
      - db
    networks:
        - main_network
  apachecnt:
      build:
        args:
          sitename: ${SITE_NAME}
        context: ./services/apache
      container_name: ${PROJECT_NAME}_apache
      image: ${PROJECT_NAME}_apache
      restart: unless-stopped
      working_dir: /var/www/html/
      volumes:
        - ./www/:/var/www/html/
        - ./services/apache/apache-conf/:/etc/apache2/sites-available/
        - ./logs/apache/:/var/log/apache2/
      environment:
        - COMPOSER_MEMORY_LIMIT=2G
        - APACHE_RUN_USER=#1000
        - APACHE_RUN_GROUP=#1000
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - db
        - rediscnt
        - phpcnt
      networks:
        - main_network
  rediscnt:
      container_name: ${PROJECT_NAME}_redis
      image: redis
      restart: unless-stopped
      ports:
        - ${REDIS_LOCAL_PORT}:6379
      volumes:
        - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./services/redis/dump:/data
        - ./logs/redis:/var/log/redis
      networks:
        - main_network
  pmacnt:
      build:
        context: ./services/phpmyadmin
      container_name: ${PROJECT_NAME}_pma
      image: ${PROJECT_NAME}_pma
      restart: unless-stopped
      volumes:
          - /sessions
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=${DB_ROOT_PASSWORD}
        - PMA_ARBITRARY=1
      ports:
        - ${PMA_LOCAL_PORT}:80
      depends_on:
        - db
      networks:
        - main_network
networks:
  main_network:
    driver: bridge
    name: ${PROJECT_NAME}_main_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}